# Generated by Django 4.0.4 on 2022-04-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spurusers', '0002_spurusers_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='spurusers',
            name='demo_budgetallocated',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spurusers',
            name='demo_budgetused',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spurusers',
            name='live_budgetallocated',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spurusers',
            name='live_budgetused',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
