# Generated by Django 4.0.4 on 2022-05-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('postalcode', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('paymentId', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('setstatus', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.PositiveIntegerField()),
                ('itemname', models.CharField(max_length=100)),
                ('itemqty', models.CharField(max_length=100)),
                ('itemcost', models.CharField(max_length=100)),
                ('itemcolor', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('itemsize', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders')),
            ],
        ),
    ]
