# Generated by Django 4.0.4 on 2022-05-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='thumbnailimage',
            field=models.TextField(blank=True),
        ),
    ]
