# Generated by Django 4.0.4 on 2022-04-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('org_address', models.FloatField()),
                ('org_telephone', models.PositiveIntegerField()),
                ('org_zip', models.PositiveIntegerField()),
                ('org_email', models.CharField(max_length=200)),
                ('org_password', models.CharField(max_length=30)),
            ],
        ),
    ]
