# Generated by Django 4.0.4 on 2022-05-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
                ('country', models.PositiveIntegerField()),
                ('telephone', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=30)),
                ('domain', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=30)),
            ],
        ),
    ]
