# Generated by Django 4.0.4 on 2022-04-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='org_address',
            field=models.CharField(max_length=200),
        ),
    ]
