# Generated by Django 4.0.4 on 2022-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_alter_org_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='company',
            field=models.CharField(default='null', max_length=30),
            preserve_default=False,
        ),
    ]
